# app/config/security.yml

security:
  provider:     in_memory

  encoders:
    Her\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_USER:         ROLE_USER
    ROLE_AUTHOR:      [ROLE_USER, ROLE_AUTHOR]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_AUTHOR, ROLE_ADMIN]
    # ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:      ^/
      anonymous:    true
      provider:     main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        # always_use_default_target_path: true
        use_referer: true
        # http://symfony.com/doc/current/security/form_login.html
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
        secret:     %secret%

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
