<?php

namespace Her\ItemsBundle\Repository;

/**
 * BatimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatimentRepository extends \Doctrine\ORM\EntityRepository
{
  public function orderAlpha()
  {
    $qb = $this->createQueryBuilder('b');
    $qb->orderBy('b.name', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
