<?php

namespace Her\ItemsBundle\Repository;

/**
 * DamageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DamageTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
