<?php

namespace Her\ItemsBundle\Repository;

/**
 * GeneralTroopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralTroopRepository extends \Doctrine\ORM\EntityRepository
{
  public function orderedEntityBarrack()
  {
    $qb = $this->createQueryBuilder('g');

    $qb
    ->where('g.barrack IS NOT NULL')
    ->orderBy('g.name', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
  public function orderedEntityDarkBarrack()
  {
    $qb = $this->createQueryBuilder('g');

    $qb
    ->where('g.darkBarrack IS NOT NULL')
    ->orderBy('g.name', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function orderedEntityHero()
  {
    $qb = $this->createQueryBuilder('g');

    $qb
    ->where('g.troopType = 2')
    ->orderBy('g.name', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
