<?php

namespace Her\ItemsBundle\Repository;

/**
 * GeneralSpecialHeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralSpecialHeroRepository extends \Doctrine\ORM\EntityRepository
{
}
