<?php

namespace Her\ItemsBundle\Repository;

/**
 * GeneralWeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralWeaponRepository extends \Doctrine\ORM\EntityRepository
{
  public function orderedEntityType($type)
  {
    $qb = $this->createQueryBuilder('w');

    $qb
    ->where('w.defense = :type')
    ->setParameter('type', $type)
    ->orderBy('w.name', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
