<?php

namespace Her\ItemsBundle\Repository;

/**
 * ProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdRepository extends \Doctrine\ORM\EntityRepository
{
  public function orderByLevelFromBatiment($batiment)
  {
    $qb = $this->createQueryBuilder('p');
    $qb->where('p.batiment = :batiment')
       ->setParameter('batiment', $batiment)
       ->orderBy('p.level', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
