<?php

namespace Her\ItemsBundle\Repository;

/**
 * SpecialHeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialHeroRepository extends \Doctrine\ORM\EntityRepository
{
}
