<?php

namespace Her\ItemsBundle\Repository;

/**
 * TargetTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
