<?php

namespace Her\ItemsBundle\Repository;

/**
 * TargetZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
