<?php

namespace Her\ItemsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TownHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownHallRepository extends \Doctrine\ORM\EntityRepository
{
  public function orderByLevel()
  {
    $qb = $this->createQueryBuilder('t');

    $qb->orderBy('t.level', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function getOrderByLevel()// pour le formulaire
  {
    return $this
      ->createQueryBuilder('t')
      ->orderBy('t.level', 'ASC')
    ;
  }
}
