<?php

namespace Her\ItemsBundle\Repository;

/**
 * TroopTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
