<?php

namespace Her\ItemsBundle\Repository;

/**
 * WeaponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponRepository extends \Doctrine\ORM\EntityRepository
{
  public function weaponOrderByLevel($name)
  {
    $qb = $this->createQueryBuilder('t');

    $qb->orderBy('t.level', 'ASC')
    ->andWhere('t.name = :name')
    ->setParameter('name',$name);
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function entityOrderByLevel($generalEntity)
  {
    $qb = $this->createQueryBuilder('t');

    $qb->orderBy('t.level', 'ASC')
    ->andWhere('t.generalWeapon = :generalWeapon')
    ->setParameter('generalWeapon',$generalEntity);
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function entityByLevel($generalWeapon, $level)
  {
    $qb = $this->createQueryBuilder('t');

    $qb->where('t.generalWeapon = :generalWeapon')
    ->setParameter('generalWeapon',$generalWeapon)
    ->andWhere('t.level = :level')
    ->setParameter('level', $level)
    ;

    return $qb
      ->getQuery()
      ->getOneOrNullResult()
    ;
  }

  public function orderByLevel()
  {
    $qb = $this->createQueryBuilder('a');

    $qb->orderBy('a.level', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function entityByTownHall($townHall)
  {
    $qb = $this->createQueryBuilder('w');

    $qb->where('w.townHall = :townHall')
    ->setParameter('townHall',$townHall)
    ->orderBy('w.generalWeapon', 'ASC')
    ->orderBy('w.level', 'ASC')
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
