<?php

namespace Her\CountBundle\Repository;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{
  public function youngerThan($days)
  {
    $limitDate = new \DateTime();
    $limitDate->modify("-".$days." day");

    $qb = $this->createQueryBuilder('v');
    $qb->orderBy('v.date', 'DESC')
    ->andWhere('v.date > :limitDate')
    ->setParameter('limitDate',$limitDate)
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function olderThan($days)
  {
    $limitDate = new \DateTime();
    $limitDate->modify("-".$days." day");

    $qb = $this->createQueryBuilder('v');
    $qb
    ->where('v.date < :limitDate')
    ->setParameter('limitDate', $limitDate)
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function byIp($days, $ip)
  {
    $limitDate = new \DateTime();
    $limitDate->modify("-".$days." day");

    $qb = $this->createQueryBuilder('v');
    $qb
    ->where('v.date < :limitDate')
    ->setParameter('limitDate', $limitDate)
    ->andWhere('v.ip = :ip')
    ->setParameter('ip', $ip)
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }

  public function byPage($days, $pageSlug)
  {
    $limitDate = new \DateTime();
    $limitDate->modify("-".$days." day");

    $qb = $this->createQueryBuilder('v');
    $qb
    ->where('v.date < :limitDate')
    ->setParameter('limitDate', $limitDate)
    ->andWhere('v.pageSlug = :pageSlug')
    ->setParameter('pageSlug', $pageSlug)
    ;

    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
